import { cookies } from "next/headers";
import { createAdminClient } from "@/lib/supabase/server";

export const SESSION_COOKIE = "kargopick-admin-session";

function generateSessionId(): string {
  return `sess_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
}

export async function createSession(): Promise<string> {
  const id = generateSessionId();

  try {
    const supabase = createAdminClient();
    await supabase
      .from("admin_sessions")
      .insert({ id, created_at: new Date().toISOString() });
  } catch {
    // Table may not exist yet; fallback to stateless random token.
  }

  return id;
}

export async function getSessionToken(): Promise<string> {
  const cookieStore = await cookies();
  return cookieStore.get(SESSION_COOKIE)?.value || "";
}

export async function verifyPassword(password: string): Promise<boolean> {
  const adminPassword = (process.env.ADMIN_PASSWORD || "admin123").trim();
  return password.trim() === adminPassword;
}

export async function isAdminAuthenticated(): Promise<boolean> {
  const token = await getSessionToken();
  if (!token) return false;

  try {
    const supabase = createAdminClient();
    const { data, error } = await supabase
      .from("admin_sessions")
      .select("id")
      .eq("id", token)
      .maybeSingle();

    if (error || !data) return false;
    return true;
  } catch {
    // If the table doesn't exist yet, accept any non-empty token
    // that was generated by our createSession() function.
    return token.startsWith("sess_");
  }
}

export async function destroySession(): Promise<void> {
  const token = await getSessionToken();
  if (!token) return;

  try {
    const supabase = createAdminClient();
    await supabase
      .from("admin_sessions")
      .delete()
      .eq("id", token);
  } catch {
    // Ignore if table doesn't exist yet.
  }
}
